/* Generated By:JavaCC: Do not edit this line. ParserTreeConstants.java Version 6.0_1 */
public interface ParserTreeConstants
{
  public int JJTVOID = 0;
  public int JJTIMPORTS = 1;
  public int JJTIMPORT = 2;
  public int JJTCLASS = 3;
  public int JJTVARDECLARATION = 4;
  public int JJTVARTYPE = 5;
  public int JJTVARID = 6;
  public int JJTMETHODDECLARATION = 7;
  public int JJTRETURNTYPE = 8;
  public int JJTMETHODBODY = 9;
  public int JJTRETURNSTATEMENT = 10;
  public int JJTMETHODPARAMS = 11;
  public int JJTMETHODPARAM = 12;
  public int JJTPARAMTYPE = 13;
  public int JJTPARAM = 14;


  public String[] jjtNodeName = {
    "void",
    "Imports",
    "Import",
    "Class",
    "VarDeclaration",
    "VarType",
    "VarId",
    "MethodDeclaration",
    "ReturnType",
    "MethodBody",
    "ReturnStatement",
    "MethodParams",
    "MethodParam",
    "ParamType",
    "Param",
  };
}
/* JavaCC - OriginalChecksum=d13bd5385f6c7ffbffb778b90dd8c13a (do not edit this line) */
